# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fvpn < Formula
  desc ""
  homepage "https://github.com/forestvpn/cli"
  version "0.1.0-beta"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/forestvpn/cli/releases/download/v0.1.0-beta/fvpn_0.1.0-beta_darwin_arm64.tar.gz"
      sha256 "88b24278a3087e64415f55d69bfa1413c1384b65246f8f900584a47a534895b4"

      def install
        bin.install "fvpn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forestvpn/cli/releases/download/v0.1.0-beta/fvpn_0.1.0-beta_darwin_amd64.tar.gz"
      sha256 "ffe21f541e612c397b99e48049ef63c5d48e2a7a36a62f7d730e9e5d5c0e55ca"

      def install
        bin.install "fvpn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/forestvpn/cli/releases/download/v0.1.0-beta/fvpn_0.1.0-beta_linux_arm64.tar.gz"
      sha256 "a44ae59f5f80ba9622577295dd8a5ec63ab3dfde95ca0dffb513faf8568bef06"

      def install
        bin.install "fvpn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forestvpn/cli/releases/download/v0.1.0-beta/fvpn_0.1.0-beta_linux_amd64.tar.gz"
      sha256 "530398bfc5e0fd77680ee6a40fcf374f60e4f7aaaeaf98251a4f20e46163acb4"

      def install
        bin.install "fvpn"
      end
    end
  end
end
